development:
  host: localhost
  database: pollum_development
  raise_not_found_error: false
  

test:
  host: localhost
  database: pollum_test
  raise_not_found_error: false
  

# set these environment variables on your prod server
production:
  host: localhost
  database: pollum_production
  raise_not_found_error: false
  
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
