development:
  host: localhost
  database: pollum_development

test:
  host: localhost
  database: pollum_test

# set these environment variables on your prod server
production:
  uri: "mongodb://steve:motherlover@pearl.mongohq.com:27073/HKPollution"
  # host: <%= ENV['MONGOID_HOST'] %>
  # port: <%= ENV['MONGOID_PORT'] %>
  # username: <%= ENV['MONGOID_USERNAME'] %>
  # password: <%= ENV['MONGOID_PASSWORD'] %>
  # database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
